config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :users, except: :destroy

  root 'posts#index'

  get 'calendar' => 'application#calendar', as: 'calendar'
  get 'documents' => 'application#documents', as: 'documents'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Authority::Abilities
  self.per_page = 10
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authority::UserAbilities
  include Authority::Abilities
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :confirmable

  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    "#{first_name.titleize} #{last_name.titleize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, only: :documents

  def calendar
    render 'layouts/calendar'
  end

  def documents
    render 'layouts/documents'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  authorize_actions_for Post, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc).paginate(:page => params[:page])
    @post_months = Post.all.group_by { |p| p.created_at.beginning_of_month}
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, flash: {success: 'Post was successfully created.'} }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, flash: {success: 'Post was successfully updated.'} }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, flash: {success: 'Post was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :authenticate_user!
  before_action :set_roles, only: :update
  authorize_actions_for User, except: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    authorize_action_for @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    set_roles
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, flash: {success: 'User was successfully created.'} }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize_action_for @user
    clean_passwords
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, flash: {success: 'User was successfully updated.'} }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,
                                    :street_address1, :street_address2, :city, :state, :zip_code, :role)
    end

    def clean_passwords
      params[:user].except!(:password, :password_confirmation)
    end

    def set_roles
      if params[:role].present?
        @user.add_role params[:role].to_sym
      elsif @user.has_role? :admin
        @user.remove_role :admin
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          Menu <i class="fa fa-bars"></i>
      </button>
      <%= link_to 'IHM Music', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if params[:controller] == 'posts' && params[:action] == 'index'%>">
          <%= link_to 'Updates', posts_path %>
        </li>
        <li class="<%= 'active' if params[:action] == 'calendar' %>">
          <%= link_to 'Calendar', calendar_path %>
        </li>
        <li class="<%= 'active' if params[:action] == 'documents' %>">
          <%= link_to 'Documents', documents_path unless current_user.nil? %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'users' %>">
          <%= link_to 'Users', users_path unless current_user.nil? %>
        </li>
        <li>
          <% if current_user.nil? && params['action'] != 'new' || params['controller'].scan('devise').present? %>
            <%= link_to "Log in", new_session_path(User.new), class: 'sign-up'  %>
          <% else %>
            <%= link_to "Log out", destroy_session_path(User), method: :delete, class: 'sign-up' %>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IHM Music</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render :partial => "layouts/navigation"%>
  <!-- Page Header -->
  <!-- Set your background image for this header on the line below. -->
  <header class="intro-header <%= Dir.glob("#{Rails.root}/app/assets/images/*bg.jpg").map {|f| File.basename(f).gsub('.jpg', '')}.sample %>">
    <div class="container">
      <%# flash.each do |name, msg| -%>
        <%# name = ['success', 'warning', 'danger', 'info'].include?(name) ? name : 'warning' %>
        <%#= content_tag :div, msg, class: "alert alert-#{name}" %>
      <%# end -%>
      <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
          <div class="site-heading">
            <h1>IHM Music Ministry</h1>
            <hr class="small">
            <span class="subheading">For All The Needs of IHM's Talented Musicians</span>
          </div>
        </div>
      </div>
    </div>
  </header>


  <!-- Main Content -->
  <div class="container">
    <%= yield %>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <ul class="list-inline text-center">
            <li>
                <a href="http://www.ihmatlanta.org" target="_blank">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-external-link fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
            <li>
                <a href="https://github.com/ghalley/ihmmusic" target="_blank">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; IHMMusic.org 2016</p>
          <p class="copyright text-muted">Theme by <a href="http://startbootstrap.com/template-overviews/clean-blog/" target="_blank">Start Bootstrap</a></p>
        </div>
      </div>
    </div>
  </footer>
</body>

<!--
  <div class="container">
    <%# flash.each do |name, msg| -%>
      <%# name = ['success', 'warning', 'danger', 'info'].include?(name) ? name : 'warning' %>
      <%#= content_tag :div, msg, class: "alert alert-#{name}" %>
    <%# end -%>
    <%#= yield %>
  </div>
 -->
</html>

app/views/layouts/calendar.html.erb
<div class="page-header">
  <h1>IHM Music Calendar</h1>
</div>
<iframe src="https://calendar.google.com/calendar/embed?title=%20&amp;showPrint=0&amp;showCalendars=0&amp;showTz=0&amp;height=600&amp;wkst=1&amp;hl=en&amp;bgcolor=%23FFFFFF&amp;src=<%= Rails.application.secrets.calendar_account %>&amp;color=%23AB8B00&amp;ctz=America%2FNew_York" style="border-width:0" width="100%" height="800" frameborder="0" scrolling="no"></iframe>

app/views/layouts/documents.html.erb
<div class="page-header">
  <h1>IHM Music Documents</h1>
</div>
<div class="panel panel-default">
  <div class="panel-body">
    <iframe src="<%= Rails.application.secrets.docs_link %>" style="width:100%; height:600px; border:0;"></iframe>
  </div>
</div>

app/views/posts/_archive.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @post_months.sort.reverse.each do |month, posts| %>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
          <%= link_to month.strftime("%B %Y"), "##{month.strftime("%B %Y").gsub(' ', '_')}", role: "button", 'data-toggle' => "collapse", 'data-parent' => "#accordion", 'aria-expanded' => "false", 'aria-controls' => month.strftime("%B %Y").gsub(' ', '_') %>
        </h4>
      </div>
      <div id="<%= month.strftime("%B %Y").gsub(' ', '_') %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <% posts.each do |post| %>
          <ul class="list-group">
            <li class="list-group-item">
              <%= link_to "#{post.title} - #{post.created_at.strftime("%m/%d")}", post_path(post) %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content, class: 'form-control', rows: 15 %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "#{params[:action] == 'edit' ? 'Save' : 'Create'}", class: 'btn btn-primary' %>
    <%= link_to 'Cancel', posts_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Update</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
  <div class="posts_archive col-md-3">
    <%= render :partial => "archive" %>
      <%= link_to 'New Update', new_post_path, class: 'btn btn-primary' if current_user && current_user.can_create?(Post) %>
  </div>

  <div class="col-lg-8 col-md-10">
    <% @posts.each do |post| %>
      <div class="post-preview">
        <a href="<%= post_path(post) %>">
          <h2 class="post-title"><%= post.title %></h2>
          <h3 class="post-subtitle">
            <%= post.content %>
          </h3>
        </a>
        <p class="post-meta">Posted on <%= post.created_at.strftime("%m/%d/%Y") %></p>
      </div>
      <hr>
    <% end -%>

    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Update</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="col-md-8">
  <h2><%= @post.title %></h2>
  <em><%= @post.created_at.strftime("%m/%d/%Y %I:%M %p") %></em>

  <p>
    <%= @post.content %>
  </p>
  <%= link_to 'Back', posts_path, class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-info' if current_user && current_user.can_update?(@post) %>
  <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' if current_user && current_user.can_delete?(@post) %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :first_name, class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :last_name, class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :email, class: 'form-control', type: 'email' %>
        </div>
      </div>
      <% if @user == current_user || !@user.persisted? %>
        <div class="form-group">
          <%= f.label :password, class: 'control-label col-sm-4' %>
          <div class="col-md-6">
            <%= f.text_field :password, class: 'form-control', type: 'password', 'aria-describedby' => "user_password_hint" %>
            <span id="user_password_hint" class="help-block">Minimum 8 characters</span>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, class: 'control-label col-sm-4' %>
          <div class="col-md-6">
            <%= f.text_field :password_confirmation, class: 'form-control', type: 'password' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label 'Street Address', class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :street_address1, class: 'form-control', type: 'text' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label 'Street Address 2', class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :street_address2, class: 'form-control', type: 'text' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :city, class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :city, class: 'form-control', type: 'text' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :state, class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :state, class: 'form-control', type: 'text' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :zip_code, class: 'control-label col-sm-4' %>
        <div class="col-md-6">
          <%= f.text_field :zip_code, class: 'form-control', type: 'text' %>
        </div>
      </div>
      <% if current_user.can_update?(User) %>
        <div class="form-group">
          <%= f.label :admin, class: 'control-label col-sm-4' %>
          <div class="col-md-6">
            <%= check_box_tag :role, 'admin', @user.has_role?(:admin) %>
          </div>
        </div>
      <% end %>

    </div>
  </div>

  <div class="form-group col-md-4">
    <div class="col-md-offset-7 col-md-10">
      <%= f.submit "#{params[:action] == 'edit' ? 'Save' : 'Create'}", class: 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit <%= @user.first_name.try(:titleize) %></h1>
<%= render :partial => "form" %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= user.street_address1 %><br/>
          <%= "#{user.street_address2}<br/>".html_safe if user.street_address2.present? %>
          <%= user.city %> <%= ", #{user.state}" if user.state.present? %> <%= user.zip_code %>
        </td>
        <td><%= link_to 'Edit', edit_user_path(user) if current_user.can_update?(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-primary' if current_user.can_create?(User) %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render :partial => "form" %>